### ISSUE TITLE
Accurate timing of gif

### ISSUE THREAD

**Issue by paulirish** [malyw/chrome-timeline-to-gif#2]
There's a timestamp (`ts`) field for all screenshots.
You could use that to put appropriate delay on each frame so it's nicely representative of the true timing.

(this project is amazing btw. nice work!)

**Comment by shospodarets** [comment]
Hey @paulirish nice idea.
Added under the "Show timing on the result video" checkbox:
http://blog.gospodarets.com/demos/chrome-timeline-to-gif/
![img](http://i.imgur.com/Y4ptzzj.gif)

**Comment by paulirish** [comment]
Oh! I actually meant something slightly different. :)  I didnt communicate clearly.

What I mean to say was applying individual delay to each frame of the GIF at encoding time, so that the GIF actually matches the pacing of the real recording.

But looking at the API of GIFEncoder it appears you can't do delay per frame. :/

**Comment by shospodarets** [comment]
@paulirish that delay is applied from the first version of this tool :)
Starting developing I checked GIFEncoder API and also didn't find explanation about making a delay for a frames.
But it appears possible using "setDelay()" after before adding a next frame- https://github.com/malyw/chrome-timeline-to-gif-demo/blob/master/js/common/components/images-to-gif.js#L43

In short- you see on the result GIF exactly the same what was in your browser (timeline is the same) :+1: 

In any case I also a added timing 😉
