### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by alanpallath** [malyw/chrome-timeline-to-gif#4]
Is there a way to add a delay between the frames?

**Comment by shospodarets** [comment]
Can you describe the case in more details-
is it to show some specific part (slide/image) of the video, or add a delay for each of them?

**Comment by alanpallath** [comment]
I meant to add delay between each of the frames. While profiling, I went through different links and finally when I made the gif using the tool, it just went so fast, I couldn't see the flow.
If it's possible to set a delay between each frame of the gif, then I suppose we can control the speed.
